-- ==============================================================================
-- SEED DATA: WEB REPUBLIC POLITIK (REPUBLIK NUSANTARA)
-- Generated automatically from initial game data
-- ==============================================================================

-- 1. DATA PENGGUNA DEMO
INSERT OR REPLACE INTO users (
  id, username, email, password_hash, full_name, title, position, 
  level, exp, max_exp, energy, max_energy, money, gold, party_id, 
  residence_region_id, perk_charisma, perk_intellect, perk_endurance, perk_connections
) VALUES (
  'usr-satria', 'satria', 'satria@nusantara.id', 'demo_hash_123', 
  'Raden Satria Nusantara', 'Kader Muda Pergerakan', 'Anggota Fraksi DPR RI', 
  4, 340, 1000, 85, 100, 75000000.0, 45, 'pdin', 
  'dki', 18, 22, 15, 16
);

-- 2. DATA PARTAI POLITIK (Murni Dibuat oleh Player)
-- Dikosongkan agar murni dibuat oleh pemain

-- 3. DATA 38 PROVINSI REPUBLIK INDONESIA
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('aceh', 'Aceh', 'Banda Aceh', 'sumatera', 5400000, 18500000000, 'pksn', 74, 'Gas Alam & Kopi Gayo', 10.0, 1, 60, 5.5483, 95.3238);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sumut', 'Sumatera Utara', 'Medan', 'sumatera', 15300000, 34200000000, 'pdin', 68, 'Kelapa Sawit & Perdagangan', 10.0, 1, 60, 3.5952, 98.6722);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sumbar', 'Sumatera Barat', 'Padang', 'sumatera', 5600000, 16000000000, 'pksn', 71, 'Semen, Pertanian & UMKM', 10.0, 1, 60, -0.9471, 100.4172);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('riau', 'Riau', 'Pekanbaru', 'sumatera', 6800000, 42000000000, 'pgr', 79, 'Minyak Bumi & Sawit', 10.0, 1, 60, 0.5071, 101.4478);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('kepri', 'Kepulauan Riau', 'Tanjungpinang / Batam', 'sumatera', 2150000, 31000000000, 'ptp', 78, 'Manufaktur Elektronik & Maritim Malaka', 10.0, 1, 60, 0.9167, 104.45);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('jambi', 'Jambi', 'Kota Jambi', 'sumatera', 3650000, 21000000000, 'pgr', 75, 'Minyak Bumi, Batubara & Karet', 10.0, 1, 60, -1.6101, 103.6131);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('bengkulu', 'Bengkulu', 'Kota Bengkulu', 'sumatera', 2080000, 15000000000, 'pdin', 72, 'Batubara & Perikanan Samudera', 10.0, 1, 60, -3.8004, 102.2655);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sumsel', 'Sumatera Selatan', 'Palembang', 'sumatera', 8750000, 29000000000, 'pgr', 76, 'Batubara, Karet & Gas', 10.0, 1, 60, -2.9909, 104.7565);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('babel', 'Kep. Bangka Belitung', 'Pangkalpinang', 'sumatera', 1520000, 19000000000, 'pdin', 76, 'Timah Terbesar Dunia & Lada Putih', 10.0, 1, 60, -2.1333, 106.1167);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('lampung', 'Lampung', 'Bandar Lampung', 'sumatera', 9150000, 22000000000, 'pdin', 70, 'Pangan, Tebu & Pelabuhan Bakauheni', 10.0, 1, 60, -5.45, 105.2667);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('banten', 'Banten', 'Serang', 'jawa', 12300000, 36000000000, 'pksn', 76, 'Baja Krakatau & Pelabuhan Merak', 10.0, 1, 60, -6.1104, 106.164);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('dki', 'DKI Jakarta', 'Jakarta Pusat', 'jawa', 10700000, 85000000000, 'ptp', 65, 'Finansial & Korporasi Global', 10.0, 1, 60, -6.2088, 106.8456);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('jabar', 'Jawa Barat', 'Bandung', 'jawa', 49800000, 62000000000, 'pgr', 72, 'Manufaktur, Otomotif & Tekstil', 10.0, 1, 60, -6.9175, 107.6191);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('jateng', 'Jawa Tengah', 'Semarang', 'jawa', 37200000, 48000000000, 'pdin', 83, 'Pangan Nasional & Kawasan Industri', 10.0, 1, 60, -7.0051, 110.4381);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('diy', 'DI Yogyakarta', 'Yogyakarta', 'jawa', 3900000, 15000000000, 'pkbr', 88, 'Pendidikan Tinggi, Budaya & Wisata', 10.0, 1, 60, -7.7956, 110.3695);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('jatim', 'Jawa Timur', 'Surabaya', 'jawa', 41100000, 58000000000, 'pkbr', 80, 'Industri Berat, Galangan Kapal & Pangan', 10.0, 1, 60, -7.2575, 112.7521);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('bali', 'Bali', 'Denpasar', 'nusa_tenggara', 4400000, 28000000000, 'pdin', 86, 'Pariwisata Internasional & Seni Budaya', 10.0, 1, 60, -8.6705, 115.2126);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('ntb', 'Nusa Tenggara Barat', 'Mataram', 'nusa_tenggara', 5450000, 19000000000, 'pksn', 73, 'Tambang Tembaga & Mandalika Sport Tourism', 10.0, 1, 60, -8.5833, 116.1167);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('ntt', 'Nusa Tenggara Timur', 'Kupang', 'nusa_tenggara', 5520000, 16000000000, 'pdin', 72, 'Peternakan, Labuan Bajo & Energi Terbarukan', 10.0, 1, 60, -10.1772, 123.607);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('kalbar', 'Kalimantan Barat', 'Pontianak', 'kalimantan', 5450000, 28000000000, 'pdin', 75, 'Bauksit, Smelter & Perbatasan Serawak', 10.0, 1, 60, -0.0263, 109.3425);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('kalteng', 'Kalimantan Tengah', 'Palangka Raya', 'kalimantan', 2750000, 23000000000, 'pdin', 78, 'Hutan Konservasi & Sawit', 10.0, 1, 60, -2.2161, 113.9139);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('kalsel', 'Kalimantan Selatan', 'Banjarbaru / Banjarmasin', 'kalimantan', 4180000, 27000000000, 'pgr', 79, 'Batubara, Intan & Pelabuhan Logistik', 10.0, 1, 60, -3.3194, 114.5908);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('kaltim', 'Kalimantan Timur (IKN)', 'IKN Nusantara / Samarinda', 'kalimantan', 3950000, 55000000000, 'pgr', 85, 'Ibu Kota Nusantara (IKN), Gas & Batubara', 10.0, 1, 60, -0.5022, 117.1536);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('kaltara', 'Kalimantan Utara', 'Tanjung Selor', 'kalimantan', 740000, 17000000000, 'ptp', 77, 'Kawasan Industri Hijau (KIPI) & Hidroelektrik', 10.0, 1, 60, 2.8427, 117.3644);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sulut', 'Sulawesi Utara', 'Manado', 'sulawesi', 2680000, 20000000000, 'pdin', 80, 'Pintu Gerbang Pasifik & Perikanan Tuna', 10.0, 1, 60, 1.4748, 124.8421);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('gorontalo', 'Gorontalo', 'Kota Gorontalo', 'sulawesi', 1220000, 14000000000, 'pksn', 74, 'Jagung Nasional & Perikanan Teluk Tomini', 10.0, 1, 60, 0.5435, 123.0568);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sulteng', 'Sulawesi Tengah', 'Palu / Morowali', 'sulawesi', 3120000, 38000000000, 'ptp', 82, 'Hilirisasi Nikel & Smelter Morowali', 10.0, 1, 60, -0.9003, 119.878);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sulbar', 'Sulawesi Barat', 'Mamuju', 'sulawesi', 1460000, 15500000000, 'pgr', 74, 'Kakao, Kelapa Sawit & Selat Makassar', 10.0, 1, 60, -2.677, 118.887);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sulsel', 'Sulawesi Selatan', 'Makassar', 'sulawesi', 9350000, 34000000000, 'pgr', 81, 'Hub Maritim Timur, Nikel Soroako & Pangan', 10.0, 1, 60, -5.1477, 119.4327);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('sultra', 'Sulawesi Tenggara', 'Kendari', 'sulawesi', 2780000, 25000000000, 'ptp', 76, 'Cadangan Bijih Nikel Terbesar Dunia', 10.0, 1, 60, -3.9985, 122.5126);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('maluku', 'Maluku', 'Ambon', 'maluku', 1920000, 16500000000, 'pdin', 77, 'Lumbung Ikan Nasional & Blok Masela', 10.0, 1, 60, -3.6547, 128.1906);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('malut', 'Maluku Utara', 'Sofifi / Weda Bay', 'maluku', 1360000, 27000000000, 'ptp', 84, 'Kawasan Industri Nikel Weda Bay & Rempah', 10.0, 1, 60, 0.73, 127.56);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('papua', 'Papua (Induk)', 'Jayapura', 'papua', 1120000, 23000000000, 'pgr', 70, 'Pusat Maritim Pasifik & Perbatasan PNG', 10.0, 1, 60, -2.5916, 140.669);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('papua_barat_induk', 'Papua Barat', 'Manokwari', 'papua', 570000, 20000000000, 'pdin', 76, 'Gas Alam Cair Tangguh & Konservasi Hayati', 10.0, 1, 60, -0.8615, 134.062);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('papua_barat', 'Papua Barat Daya', 'Sorong / Raja Ampat', 'papua', 630000, 18500000000, 'pdin', 77, 'Minyak Kasim & Pariwisata Bahari Raja Ampat', 10.0, 1, 60, -0.8762, 131.2558);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('papua_tengah', 'Papua Tengah', 'Nabire / Grasberg', 'papua', 1460000, 45000000000, 'pgr', 75, 'Tambang Emas & Tembaga Terbesar Grasberg', 10.0, 1, 60, -3.3667, 135.4833);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('papua_selatan', 'Papua Selatan', 'Merauke', 'papua', 530000, 22000000000, 'pgr', 78, 'Kawasan Pangan Nasional (Food Estate) & Perbatasan', 10.0, 1, 60, -8.4991, 140.4011);
INSERT OR REPLACE INTO regions (id, name, capital, island, population, budget, dominant_party_id, support_rate, resource, tax_rate, infrastructure_level, defense_power, lat, lng) VALUES ('papua_pegunungan', 'Papua Pegunungan', 'Wamena', 'papua', 1430000, 17500000000, 'pksn', 71, 'Kopi Arabika Wamena & Hasil Bumi Lembah Baliem', 10.0, 1, 60, -4.0984, 138.9439);

-- 4. DATA RANCANGAN UNDANG-UNDANG DPR RI
INSERT OR REPLACE INTO bills (id, title, description, category, author_id, author_name, party_id, yes_votes, no_votes, status, impact_summary) VALUES ('bill-tax-reform', 'RUU Pajak Karbon & Insentif Hilirisasi Nikel', 'Mengenakan pajak karbon progresif pada pabrik smelter luar negeri dan memberikan insentif 20% bagi industri hilirisasi domestik di Morowali & Weda Bay.', 'Ekonomi & Tambang', 'usr-satria', '', 'pdin', 0, 0, 'voting', '');
INSERT OR REPLACE INTO bills (id, title, description, category, author_id, author_name, party_id, yes_votes, no_votes, status, impact_summary) VALUES ('bill-military-radar', 'RUU Peningkatan Anggaran Radar Pertahanan ZEE Natuna & Papua', 'Mengalokasikan tambahan 15% dari APBN untuk pemasangan sistem radar pertahanan maritim generasi ke-5 serta pangkalan kapal selam di Natuna dan Sorong.', 'Pertahanan & Kedaulatan', 'usr-satria', '', 'pdin', 0, 0, 'voting', '');
INSERT OR REPLACE INTO bills (id, title, description, category, author_id, author_name, party_id, yes_votes, no_votes, status, impact_summary) VALUES ('bill-subsidy-umkm', 'RUU Bantuan Tunai & Subsidi Pupuk Petani Desa', 'Menjamin ketersediaan pupuk bersubsidi 100% dan pinjaman lunak bunga 0% untuk 12 juta keluarga petani di Jawa, Sumatera, dan Nusa Tenggara.', 'Kesejahteraan Sosial', 'usr-satria', '', 'pdin', 0, 0, 'voting', '');

-- 5. DATA UNDANG-UNDANG NASIONAL YANG TELAH DISAHKAN
INSERT OR REPLACE INTO passed_laws (id, title, category, description, national_effects) VALUES ('law-ikn-transfer', 'UU Pemindahan Ibu Kota Negara ke Nusantara (IKN)', 'Tata Negara', '', '{}');
INSERT OR REPLACE INTO passed_laws (id, title, category, description, national_effects) VALUES ('law-bpjs-universal', 'UU Jaminan Pelayanan Medis Semesta (BPJS Rakyat)', 'Kesehatan', '', '{}');
INSERT OR REPLACE INTO passed_laws (id, title, category, description, national_effects) VALUES ('law-threshold-parliament', 'UU Ambang Batas Parlemen (Parliamentary Threshold 4%)', 'Pemilu & Parlemen', '', '{}');

-- 6. DATA PEMILU & KANDIDAT PRESIDEN
INSERT OR REPLACE INTO elections (id, title, type, term, status, end_time) VALUES ('pemilu-2026', 'Pemilihan Presiden & Wakil Presiden Republik Nusantara', 'presidential', '2026-2031', 'active', datetime('now', '+3 days'));
INSERT OR REPLACE INTO candidates (id, election_id, name, running_mate, party_id, votes, vision, promises, color) VALUES ('cand-1', 'pemilu-2026', 'Jend. (Purn) Prabowo Kusumo & Gibran Rakabumi', '', 'pdin', 0, '', '[]', '#f59e0b');
INSERT OR REPLACE INTO candidates (id, election_id, name, running_mate, party_id, votes, vision, promises, color) VALUES ('cand-2', 'pemilu-2026', 'Ganjar Pranowo & Mahfud M.D.', '', 'pdin', 0, '', '[]', '#dc2626');
INSERT OR REPLACE INTO candidates (id, election_id, name, running_mate, party_id, votes, vision, promises, color) VALUES ('cand-3', 'pemilu-2026', 'Anies Baswedan & Muhaimin Iskandar', '', 'pdin', 0, '', '[]', '#f97316');

-- 7. DATA KORAN PERS NASIONAL
INSERT OR REPLACE INTO articles (id, title, content, category, author_id, author_name, author_title, newspaper_name, views, upvotes) VALUES ('art-1', '', 'Gedung Nusantara DPR RI bergemuruh saat fraksi oposisi mempertanyakan lonjakan anggaran belanja radar pertahanan. Sementara itu, kubu pemerintah menegaskan bahwa kedaulatan laut nusantara tidak dapat dikompromikan.', 'Parlemen', 'usr-satria', 'Redaksi Harian Garuda', '', 'Harian Nusantara', 100, 840);
INSERT OR REPLACE INTO articles (id, title, content, category, author_id, author_name, author_title, newspaper_name, views, upvotes) VALUES ('art-2', '', 'Kementerian Perindustrian mengumumkan surplus perdagangan kuartal ini didorong oleh 14 smelter baru yang beroperasi penuh di Morowali dan Weda Bay. Partai Teknokrat mendorong dividen diarahkan untuk beasiswa riset.', 'Ekonomi', 'usr-satria', 'Warta Ekonomi Republik', '', 'Harian Nusantara', 100, 620);
INSERT OR REPLACE INTO articles (id, title, content, category, author_id, author_name, author_title, newspaper_name, views, upvotes) VALUES ('art-3', '', 'Simulasi Pilpres terbaru menunjukkan elektabilitas tiga poros utama masih berada di rentang 28% - 35%. Suara pemilih di Jawa Tengah, Jawa Barat, dan Jawa Timur diprediksi menjadi medan tempur penentu kemenangan mutlak.', 'Pemilu', 'usr-satria', 'Lembaga Indikator Politik Nusantara', '', 'Harian Nusantara', 100, 1950);

-- 8. DATA KAWASAN GEOPOLITIK DUNIA
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('malaysia', 'MY', 'MYS', 'Federasi Malaysia', 'Kuala Lumpur', '🇲🇾', 'asean', 34.3, 'ASEAN • Non-Blok', 'Mitra Serumpun & Sekutu', 'Minyak Mentah, Sawit & Semikonduktor', 76, 'Monarki Konstitusional Federal', '+88% (Sangat Harmonis)', 'Negara tetangga terdekat di Selat Malaka & Kalimantan Utara. Mitra kunci perdagangan maritim Nusantara.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('singapore', 'SG', 'SGP', 'Republik Singapura', 'Singapura', '🇸🇬', 'asean', 5.9, 'ASEAN • Global Hub', 'Mitra Finansial Utama', 'Pusat Keuangan Global & Kilang Maritim', 84, 'Republik Parlementer', '+85% (Kemitraan Strategis)', 'Pusat logistik dan keuangan terbesar di Asia Tenggara dengan armada pertahanan modern canggih.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('philippines', 'PH', 'PHL', 'Republik Filipina', 'Manila', '🇵🇭', 'asean', 115.6, 'ASEAN • Pasifik', 'Mitra Keamanan Maritim', 'Nikel, Tembaga & Jasa Teknologi', 72, 'Republik Presidensial', '+80% (Bilateral Stabil)', 'Kepulauan tetangga di utara Sulawesi. Bekerja sama dalam patroli perairan Laut Sulawesi & Sulu.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('thailand', 'TH', 'THA', 'Kerajaan Thailand', 'Bangkok', '🇹🇭', 'asean', 71.8, 'ASEAN • Lumbung Pangan', 'Mitra Perdagangan Pangan', 'Beras, Otomotif & Karet Alam', 78, 'Monarki Konstitusional', '+82% (Mitra Dagang Aktif)', 'Kekuatan ekonomi daratan Asia Tenggara, lumbung pangan dan pusat manufaktur otomotif regional.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('vietnam', 'VN', 'VNM', 'Republik Sosialis Vietnam', 'Hanoi', '🇻🇳', 'asean', 98.2, 'ASEAN • Industri Manufaktur', 'Mitra Strategis Komprehensif', 'Elektronika, Tekstil & Minyak Bumi', 83, 'Republik Sosialis Satu Partai', '+84% (Sangat Erat)', 'Kekuatan militer darat teruji dan pusat manufaktur yang berkembang sangat pesat di Laut Cina Selatan.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('brunei', 'BN', 'BRN', 'Negara Brunei Darussalam', 'Bandar Seri Begawan', '🇧🇳', 'asean', 0.5, 'ASEAN • Petrodolar Serumpun', 'Sahabat Serumpun', 'Minyak Bumi & Gas Alam Cair (LNG)', 65, 'Monarki Absolut Islam Melayu', '+90% (Sangat Harmonis)', 'Kesultanan kaya minyak di pantai barat laut pulau Kalimantan yang bertetangga erat dengan Indonesia.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('timor_leste', 'TL', 'TLS', 'Republik Demokratik Timor Leste', 'Dili', '🇹🇱', 'asean', 1.3, 'Calon Anggota ASEAN • Pasifik', 'Tetangga Perbatasan Darat', 'Minyak Lepas Pantai & Kopi Organik', 55, 'Republik Semi-Presidensial', '+94% (Persaudaraan & Rekonsiliasi Erat)', 'Berbatasan darat langsung dengan Nusa Tenggara Timur (NTT). Indonesia adalah pendukung utama keanggotaan penuh ASEAN.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('papua_new_guinea', 'PG', 'PNG', 'Negara Independen Papua Nugini', 'Port Moresby', '🇵🇬', 'africa_oceania', 10.1, 'Pasifik • Melanesian Spearhead Group', 'Mitra Perbatasan Darat Timur', 'Emas, Gas Alam & Hasil Hutan', 62, 'Monarki Konstitusional Parlementer', '+86% (Stabilitas Perbatasan)', 'Berbatasan darat langsung sepanjang 820 km di Pulau Papua dari Jayapura hingga Merauke.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('australia', 'AU', 'AUS', 'Persemakmuran Australia', 'Canberra', '🇦🇺', 'africa_oceania', 26.5, 'AUKUS • Pasifik Selatan', 'Tetangga Strategis Selatan', 'Uranium, Gas Alam, Batubara & Gandum', 88, 'Monarki Konstitusional Parlementer', '+78% (Dinamis & Konstruktif)', 'Kekuatan benua selatan yang berbatasan laut langsung dengan perairan Nusa Tenggara, Bali, dan Papua Selatan.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('new_zealand', 'NZ', 'NZL', 'Selandia Baru', 'Wellington', '🇳🇿', 'africa_oceania', 5.2, 'Five Eyes • Pasifik', 'Mitra Peternakan & Energi Hijau', 'Susu, Daging, Panas Bumi & Pariwisata', 70, 'Monarki Konstitusional Parlementer', '+80% (Bilateral Erat)', 'Negara kepulauan modern di Pasifik Barat Daya, penyuplai utama produk susu olahan ke pasar Indonesia.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('china', 'CN', 'CHN', 'Republik Rakyat Tiongkok', 'Beijing', '🇨🇳', 'east_asia', 1412, 'BRICS • Superpower', 'Mitra Dagang & Investasi Terbesar', 'Manufaktur Raksasa, Rare Earth & Baja', 98, 'Republik Sosialis', '+81% (Investasi Tinggi)', 'Kekuatan ekonomi dan manufaktur global. Investor infrastruktur dan pengolah nikel terbesar di Nusantara.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('japan', 'JP', 'JPN', 'Negara Jepang', 'Tokyo', '🇯🇵', 'east_asia', 124.5, 'G7 • Aliansi Pasifik', 'Mitra Teknologi & Pembangunan', 'Robotika, Otomotif & Teknologi Maritim', 91, 'Monarki Konstitusional Parlementer', '+86% (Kemitraan Erat)', 'Pionir industri teknologi presisi dan armada maritim modern di kawasan Pasifik Utara.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('south_korea', 'KR', 'KOR', 'Republik Korea (Korea Selatan)', 'Seoul', '🇰🇷', 'east_asia', 51.7, 'G20 • Aliansi Industri', 'Mitra Dirgantara & Baterai EV', 'Baterai Listrik, Semikonduktor & Alutsista', 93, 'Republik Presidensial', '+85% (Proyek Jet Tempur KFX/IFX)', 'Mitra bersama dalam pengembangan pesawat tempur generasi 4.5 dan ekosistem rantai pasok EV nasional.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('north_korea', 'KP', 'PRK', 'Republik Demokratik Rakyat Korea', 'Pyongyang', '🇰🇵', 'east_asia', 26, 'Non-Blok Historis • Kekuatan Nuklir', 'Hubungan Diplomatik Sejarah (Soekarno)', 'Batubara, Mineral & Teknologi Rudal', 86, 'Republik Sosialis Juche', '+75% (Hubungan Sejarah Bunga Kimilsungia)', 'Memiliki hubungan diplomatik unik bersejarah dengan Indonesia sejak era Presiden Soekarno.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('saudi_arabia', 'SA', 'SAU', 'Kerajaan Arab Saudi', 'Riyadh', '🇸🇦', 'mid_east_south', 36.4, 'OPEC • BRICS • Liga Arab', 'Mitra Energi & Spiritual Global', 'Minyak Mentah Cadangan Dunia & Petrokimia', 82, 'Monarki Absolut', '+92% (Hubungan Istimewa Haji & Energi)', 'Raksasa energi global pemegang kendali pasar minyak dunia serta pusat ziarah spiritual umat Islam dunia.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('uae', 'AE', 'ARE', 'Uni Emirat Arab', 'Abu Dhabi', '🇦🇪', 'mid_east_south', 9.5, 'OPEC • Sovereign Wealth Hub', 'Investor Strategis Ibu Kota Baru', 'Finansial Global, Penerbangan & Energi Hijau', 79, 'Federasi Monarki', '+90% (Investor Kunci IKN Nusantara)', 'Pusat perdagangan dan investasi multinasional di Teluk Persia dengan sovereign wealth fund raksasa.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('india', 'IN', 'IND', 'Republik India', 'New Delhi', '🇮🇳', 'mid_east_south', 1428, 'BRICS • Samudra Hindia', 'Mitra Maritim Samudra Hindia', 'Teknologi Informasi, Farmasi & Baja', 95, 'Republik Parlementer Federal', '+83% (Perjanjian Sabang-Andaman)', 'Kekuatan demografi terbesar di dunia, berbatasan laut di ujung barat Sabang via Kepulauan Andaman & Nikobar.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('turkey', 'TR', 'TUR', 'Republik Türkiye', 'Ankara', '🇹🇷', 'mid_east_south', 85.3, 'NATO • Eurasia Bridge', 'Mitra Industri Pertahanan', 'Drone Tempur (UAV), Baja & Pertanian', 89, 'Republik Presidensial', '+88% (Mitra Alutsista & Kapal Perang)', 'Jembatan geopolitik antara Eropa dan Asia dengan teknologi drone tempur dan alutsista terdepan.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('iran', 'IR', 'IRN', 'Republik Islam Iran', 'Tehran', '🇮🇷', 'mid_east_south', 88.5, 'BRICS • Selat Hormuz', 'Mitra Energi & Gerakan Non-Blok', 'Minyak, Gas, Drone & Teknologi Nuklir', 85, 'Teokrasi Republik Islam', '+79% (Hubungan Perdagangan Netral)', 'Penguasa perairan strategis Selat Hormuz dengan pengaruh geopolitik kuat di Timur Tengah.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('russia', 'RU', 'RUS', 'Federasi Rusia', 'Moskow', '🇷🇺', 'europe', 144.2, 'BRICS • Superpower Eurasia', 'Mitra Strategis Alutsista & Nuklir', 'Gas Bumi, Minyak, Uranium & Gandum', 97, 'Republik Semi-Presidensial Federal', '+83% (Hubungan Bersejarah Kuat)', 'Negara dengan daratan terluas di dunia, memiliki cadangan energi fosil dan persenjataan nuklir terbesar.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('united_kingdom', 'GB', 'GBR', 'Kerajaan Bersatu (Inggris / UK)', 'London', '🇬🇧', 'europe', 67.7, 'NATO • G7 • Dewan Keamanan PBB', 'Mitra Finansial & Maritim Global', 'Jasa Keuangan, Teknologi Kedirgantaraan', 90, 'Monarki Konstitusional Parlementer', '+78% (Mitra Maritim & Pendidikan)', 'Pusat moneter global City of London dan kekuatan diplomasi internasional pemegang hak veto PBB.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('germany', 'DE', 'DEU', 'Republik Federal Jerman', 'Berlin', '🇩🇪', 'europe', 84.4, 'Uni Eropa • G7 • Pemimpin Ekonomi', 'Mitra Industri Mesin & Riset', 'Teknik Presisi, Otomotif & Energi Terbarukan', 85, 'Republik Federal Parlementer', '+82% (Kemitraan Teknologi Hijau)', 'Motor ekonomi terkuat di Benua Eropa dengan standar keunggulan manufaktur presisi industri 4.0.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('france', 'FR', 'FRA', 'Republik Prancis', 'Paris', '🇫🇷', 'europe', 68, 'Uni Eropa • NATO • Veto PBB', 'Pemasok Jet Tempur Rafale & Kapal Selam', 'Dirgantara (Airbus/Dassault), Nuklir & Mewah', 92, 'Republik Semi-Presidensial', '+87% (Kerjasama Strategis Pertahanan RI)', 'Kekuatan diplomasi dan industri alutsista terkemuka Eropa, mitra pengadaan jet tempur generasi 4.5 Rafale RI.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('netherlands', 'NL', 'NLD', 'Kerajaan Belanda', 'Amsterdam', '🇳🇱', 'europe', 17.8, 'Uni Eropa • NATO • Gerbang Eropa', 'Pintu Gerbang Ekspor Sawit ke Eropa', 'Pelabuhan Rotterdam, Semikonduktor (ASML) & Maritim', 79, 'Monarki Konstitusional Parlementer', '+83% (Hubungan Sejarah & Kerjasama Hukum)', 'Pusat logistik pelabuhan terbesar di Eropa (Rotterdam) dan produsen mesin semikonduktor paling canggih di dunia.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('usa', 'US', 'USA', 'Amerika Serikat (USA)', 'Washington D.C.', '🇺🇸', 'americas', 334.9, 'NATO • G7 • Superpower Ekonomi', 'Mitra Strategis Komprehensif', 'Dolar AS, Teknologi Digital (Silicon Valley) & Alutsista', 100, 'Republik Presidensial Federal Konstitusional', '+80% (Kemitraan Bebas Aktif)', 'Kekuatan ekonomi dan pertahanan global terbesar di dunia dengan jangkauan militer lintas samudra.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('canada', 'CA', 'CAN', 'Kanada', 'Ottawa', '🇨🇦', 'americas', 39.5, 'G7 • NATO • Persemakmuran', 'Mitra Perjanjian Dagang CEPA', 'Nikel, Gandum, Minyak & Potasium', 80, 'Monarki Konstitusional Parlementer Federal', '+81% (Perdagangan Komoditas)', 'Negara terluas kedua di dunia dengan cadangan mineral kritis dan hasil hutan berlimpah.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('brazil', 'BR', 'BRA', 'Republik Federatif Brasil', 'Brasilia', '🇧🇷', 'americas', 215.3, 'BRICS • Pemimpin Amerika Latin', 'Mitra Hutan Hujan & Agrikultur', 'Kedelai, Daging, Bijih Besi & Biofuel', 81, 'Republik Presidensial Federal', '+83% (Aliansi Negara Hutan Hujan Tropis)', 'Pemegang paru-paru dunia Amazon, bersekutu dengan Indonesia dalam diplomasi iklim dan pasar komoditas.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('argentina', 'AR', 'ARG', 'Republik Argentina', 'Buenos Aires', '🇦🇷', 'americas', 46.2, 'G20 • Segitiga Litium', 'Mitra Pangan & Cadangan Litium', 'Litium, Kedelai, Gandum & Daging Sapi', 73, 'Republik Presidensial Federal', '+80% (Mitra Litium Baterai EV)', 'Bagian dari Segitiga Litium dunia di Amerika Selatan, mitra strategis pengembangan bahan baku baterai.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('south_africa', 'ZA', 'ZAF', 'Republik Afrika Selatan', 'Pretoria', '🇿🇦', 'africa_oceania', 60.4, 'BRICS • G20 • Samudra Atlantik-Hindia', 'Mitra Gerakan Non-Blok', 'Platinum, Emas, Berlian & Batubara', 74, 'Republik Parlementer', '+84% (Diplomasi Konferensi Asia Afrika)', 'Raksasa tambang mineral berharga Afrika, memiliki keterikatan sejarah diplomasi kuat dengan Indonesia sejak KAA 1955.');
INSERT OR REPLACE INTO world_regions (id, iso2, iso3, name, capital, flag, sector, population, bloc, diplomatic_status, dominant_resource, military_power, government_type, relations_with_ri, description) VALUES ('egypt', 'EG', 'EGY', 'Republik Arab Mesir', 'Kairo', '🇪🇬', 'africa_oceania', 110.9, 'BRICS • Terusan Suez • Liga Arab', 'Negara Pertama Pengakui Kemerdekaan RI', 'Terusan Suez, Gas Alam & Pariwisata Kuno', 87, 'Republik Presidensial', '+95% (Sekutu Historis Sejati)', 'Penguasa Terusan Suez rute pelayaran maritim dunia, dan negara pertama di dunia yang mengakui de jure kemerdekaan RI 1945.');

-- 9. DATA TRAKTAT & PERJANJIAN INTERNASIONAL AWAL
INSERT OR REPLACE INTO diplomatic_treaties (id, world_region_id, treaty_type, title, description, status) VALUES ('trt-mys-1', 'malaysia', 'defense', 'Pakta Kerjasama Patroli Perbatasan Selat Malaka & Selat Karimata', 'Perjanjian patroli angkatan laut bersama untuk menjaga stabilitas jalur pelayaran tersibuk di dunia.', 'active');
INSERT OR REPLACE INTO diplomatic_treaties (id, world_region_id, treaty_type, title, description, status) VALUES ('trt-sgp-1', 'singapore', 'trade', 'Pusat Kliring Finansial & Logistik Pelabuhan Maritim Nusantara', 'Kemudahan bebas bea transit komoditas nikel dan bauksit olahan ke hub logistik Singapura.', 'active');
INSERT OR REPLACE INTO diplomatic_treaties (id, world_region_id, treaty_type, title, description, status) VALUES ('trt-sau-1', 'saudi_arabia', 'cultural', 'Perjanjian Kuota Ziarah Haji & Pasokan Minyak Mentah Strategis', 'Pengamanan pasokan energi minyak fosil cadangan nasional dan fasilitas khusus jamaah RI.', 'active');
